"""Initial schema baseline.

Creates all Intelli-Credit tables from the ORM metadata. Using the metadata
keeps this baseline in lock-step with the models; subsequent schema changes
should be added as new autogenerated revisions.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-01
"""

from __future__ import annotations

from alembic import op

import models.db_models  # noqa: F401  (registers ORM models on Base.metadata)
from config.database import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create every table defined on the ORM metadata."""
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Drop every table defined on the ORM metadata."""
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
